In [66]:
import plotly.express as px  
import dash  
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
name = 'TOYA'

In [68]:
df = pd.read_html('https://www.biznesradar.pl/raporty-finansowe-rachunek-zyskow-i-strat/'+name+',Q')[-3].drop([
                                                                                    0,6,7,8,9,10,11,12,13,15,17]).set_index('Unnamed: 0')
shares = pd.read_html('https://www.biznesradar.pl/wskazniki-wartosci-rynkowej/'+name)[0].drop([0,2,3,4,5,6,7,8,9
                                                                                             ,10,11,12,13,14,15]).set_index('Unnamed: 0')


del df["Unnamed: "+str(len(df.columns))]  
del shares["Unnamed: "+str(len(shares.columns))] 

df = df.drop(df.columns[0:4], axis=1)
shares = shares.drop(shares.columns[0:(len(shares.columns)-len(df.columns))]   ,axis=1)
df.columns = df.columns.str.slice(start=2 , stop=7)
shares.columns = df.columns
     
for i in range(len(df.columns)):
    df[str(df.columns[i])] = df[str(df.columns[i])].str.replace('(k/k).*','')
    df[str(df.columns[i])] = df[str(df.columns[i])].str.replace('(r/r).*','')
    df[str(df.columns[i])] = df[str(df.columns[i])].str.replace(' ','')
    shares[str(shares.columns[i])] = shares[str(shares.columns[i])].str.replace(' ','')
    

df = df.apply(pd.to_numeric, errors='ignore')
shares = shares.apply(pd.to_numeric, errors='ignore')
df

,12/Q1,12/Q2,12/Q3,12/Q4,13/Q1,13/Q2,13/Q3,13/Q4,14/Q1,14/Q2,...,18/Q2,18/Q3,18/Q4,19/Q1,19/Q2,19/Q3,19/Q4,20/Q1,20/Q2,20/Q3
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
Przychody ze sprzedaży,48930,55699,50485,46133,56549,65677,62574,57910,62645,67091,...,94047,96061,102294,106655,109507,109056,114800,119295,136818,128850
Techniczny koszt wytworzenia produkcji sprzedanej,32079,36561,34268,31555,37648,42666,40742,38396,40737,43192,...,56930,61444,65944,66543,69347,69778,76132,76024,87742,84152
Koszty sprzedaży,6723,7164,6836,6758,8218,9914,9628,11503,10705,11540,...,15603,17123,19632,19861,20227,19071,18803,20013,21694,20188
Koszty ogólnego zarządu,3105,2839,2478,3056,2769,3094,2749,3229,2981,2744,...,4952,5136,6158,4971,5027,5322,5691,5831,6503,5551
Zysk ze sprzedaży,7023,9135,6903,4764,7914,10003,9455,4782,8222,9615,...,16562,12358,10560,15280,14906,14885,14174,17427,20879,18959
Zysk przed opodatkowaniem,4716,8807,5354,3562,8001,9731,9145,5223,7705,9344,...,17092,13374,10356,14393,15081,15003,11710,16494,21876,18187
Zysk netto,3594,7026,4254,2769,6416,7751,7357,4142,6150,7571,...,13703,10875,8327,11564,11952,12237,9072,13225,17724,14857
EBITDA,6279,9815,6569,5082,9001,10488,9859,5876,8465,10116,...,18408,14792,11882,16645,17293,17193,14073,19187,24861,21838

In [70]:
time = df.columns
shares = shares.iloc[0]
year = [ time[i] for i in range(3,len(time),4)]
year = np.append(year , " 'Q4 ")
sell_revenue = df.iloc[0]
Revenue_year = [np.sum(sell_revenue[i:i+4])/1000000 for i in range(0,len(sell_revenue),4)] 
production_costs = df.iloc[1]
sell_costs = df.iloc[2]
board_costs = df.iloc[3]
sell_profit = df.iloc[4]
gross_profit = df.iloc[5]

net_profit = df.iloc[6]
net_profit_share = net_profit/shares*1000
net_profit_share_year = [ np.sum(net_profit_share[i:i+4]) for i in range(0,len(net_profit_share),4) ]
polynomial_coeff = np.polyfit([i for i in range(0,len(time))], net_profit_share, 1)
curve = np.polyval(polynomial_coeff, [i for i in range(0,len(time))])
        
Revenue_1Q = [ sell_revenue[i]/1000 for i in range(0,len(sell_revenue),4)]
Revenue_2Q = [ sell_revenue[i]/1000 for i in range(1,len(sell_revenue),4)]
Revenue_3Q = [ sell_revenue[i]/1000 for i in range(2,len(sell_revenue),4)]
Revenue_4Q = [ sell_revenue[i]/1000 for i in range(3,len(sell_revenue),4)]

gross_profit_1Q = [ gross_profit[i]/1000 for i in range(0,len(sell_revenue),4)]
gross_profit_2Q = [ gross_profit[i]/1000 for i in range(1,len(sell_revenue),4)]
gross_profit_3Q = [ gross_profit[i]/1000 for i in range(2,len(sell_revenue),4)]
gross_profit_4Q = [ gross_profit[i]/1000 for i in range(3,len(sell_revenue),4)]

In [73]:
fig = make_subplots(specs=[[{"secondary_y": False}]])
fig_Q = make_subplots(rows=2, cols=2, specs=[[{"secondary_y": True}, {"secondary_y": True}], [{"secondary_y": True}, {"secondary_y": True}]])

def figure(typo,x, y, name,color, xlabel, ylabel):
    fig.update_xaxes(title_text= xlabel)
    fig.update_yaxes(title_text= ylabel)

    return  fig.add_trace(typo(x= x, y= y, name= name, marker=dict(color=color )))

def figure_Q(typo, x, y, name, row, column, color):
    return fig_Q.add_trace(typo(x=x, y=y, name = name, marker=dict(color=color )), row=row, col=column, secondary_y=False)



# ------------------ Quartly results

figure_ = figure_Q(go.Scatter, [time[i] for i in range(0,len(sell_revenue),4)], Revenue_1Q, row=1, column=1 , name='Revenue', color='Navy'       )
figure_Q1 = figure_Q(go.Scatter, [time[i] for i in range(0,len(sell_revenue),4)], gross_profit_1Q, row=1, column=1 , name='Revenue', color='Orange'       )

figure_ = figure_Q(go.Scatter, [time[i] for i in range(1,len(sell_revenue),4)], Revenue_2Q, row=1, column=2 , name='Revenue', color='Navy'       )
figure_Q2 = figure_Q(go.Scatter, [time[i] for i in range(1,len(sell_revenue),4)], gross_profit_2Q, row=1, column=2 , name='Revenue', color='Orange'       )

figure_ = figure_Q(go.Scatter, [time[i] for i in range(2,len(sell_revenue),4)], Revenue_3Q, row=2, column=1 , name='Revenue', color='Navy'      )
figure_Q3 = figure_Q(go.Scatter, [time[i] for i in range(2,len(sell_revenue),4)], gross_profit_3Q, row=2, column=1 , name='Revenue', color='Orange'       )

figure_ = figure_Q(go.Scatter, [time[i] for i in range(3,len(sell_revenue),4)], Revenue_4Q, row=2, column=2 , name='Revenue', color='Navy'       )



# -------------------------------------------------------------------------- App layout
app = dash.Dash(__name__)




app.layout = html.Div(
    children=[
        html.H1(children="Web Dashboard", style = {'textAlign':'center'}),
        
        dcc.Graph(figure= figure(go.Bar,time, sell_revenue, 'Revenue per Q', 'Blue', 'time',ylabel=None)),   
        
        dcc.Graph(figure= figure(go.Bar,year, Revenue_year,  'Revenue per Year', 'Navy', 'time',ylabel=None)),  
        










        #dcc.Graph(figure = figure_Q(go.Scatter, [time[i] for i in range(3,len(sell_revenue),4)], gross_profit_4Q, row=2,column=2 , name='Gross Profit', color='Orange'       )),

        
    
# ----------------------------------------------------------------------- Earnings
        #dcc.Graph(figure= figure(go.Bar, time, net_profit_share, name = 'EPS',color='Green')), 
        #dcc.Graph(figure= figure(go.Scatter, time, curve, name = 'Curve', color='Lime')),
        #dcc.Graph(figure= figure(go.Bar,year, net_profit_share_year, name = 'Yearly EPS', color= 'Lime') ),
                
        
        
      
        
        
    ]
)

In [74]:
if __name__ == '__main__':
    app.run_server( use_reloader=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Feb/2021 19:37:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2021 19:37:06] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2021 19:37:06] "GET /_dash-dependencies HTTP/1.1" 200 -